version: '3.7'

services:
  backend:
    build:
      context: ./Backend/simple-api-student-main
    networks:
            - app-network
    depends_on:
            - database
    container_name : my-running-studentjava-app

  database:
    build:
        context: ./Database
    networks:
        - app-network
    volumes:
        - my_volume:/var/lib/postgresql/data
    container_name : my-postgres

  httpd:
        build:
            context: ./Http_server
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - backend
        container_name : my-apache-container

networks:
    app-network:
volumes:
    my_volume:
